import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Poppins, Merriweather } from "next/font/google";
import { dark } from "@clerk/themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const merriweather = Merriweather({
  weight: ["700"],
  subsets: ["latin"],
  variable: "--font-merriweather",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        variables: {
          colorBackground: `hsl(20 14.3% 4.1%)`,
          fontFamily: `var(--font-poppins)`,
          colorPrimary: "hsl(20.5 90.2% 48.2%)",
        },
      }}
    >
      <html lang="en">
        <body
          className={`${merriweather.variable} font-sans ${poppins.variable} dark antialiased`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
